# Generated by Django 3.1.4 on 2021-01-25 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20201224_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Position Shifts',
            },
        ),
        migrations.AlterModelOptions(
            name='eventpositionrequest',
            options={},
        ),
        migrations.DeleteModel(
            name='eventpositionrequest'
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='events.positionshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shift Requests',
            },
        ),
        migrations.AddField(
            model_name='positionshift',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='events.eventposition'),
        ),
        migrations.AddField(
            model_name='positionshift',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_positions', to=settings.AUTH_USER_MODEL),
        ),
    ]
