# Generated by Django 3.1.4 on 2021-02-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210125_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventposition',
            name='user',
        ),
    ]
