# Generated by Django 3.1.7 on 2021-03-19 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_remove_eventposition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionshift',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_shifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
