# Generated by Django 3.1.7 on 2021-04-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210319_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionshift',
            name='end',
        ),
        migrations.RemoveField(
            model_name='positionshift',
            name='start',
        ),
    ]
