# Generated by Django 3.1.7 on 2021-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210422_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('positions', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Position Presets',
            },
        ),
    ]
