# Generated by Django 3.1.7 on 2021-05-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_positionpreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event'},
        ),
        migrations.AlterModelOptions(
            name='eventposition',
            options={'verbose_name': 'Event position'},
        ),
        migrations.AlterModelOptions(
            name='positionpreset',
            options={'verbose_name': 'Position preset'},
        ),
        migrations.AlterModelOptions(
            name='positionshift',
            options={'verbose_name': 'Position shift'},
        ),
        migrations.AlterModelOptions(
            name='shiftrequest',
            options={'verbose_name': 'Shift request'},
        ),
        migrations.AlterModelOptions(
            name='supportrequest',
            options={'verbose_name': 'Event support request'},
        ),
    ]
