# Generated by Django 3.2.4 on 2023-10-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210509_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='requested_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
