# Generated by Django 3.2.4 on 2023-10-20 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_supportrequest_requested_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('notes', models.JSONField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event score',
            },
        ),
    ]
