# Generated by Django 5.0.3 on 2024-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('poly', 'Policy'), ('proc', 'Procedure'), ('loa', 'LOA'), ('vatis', 'vATIS Profile'), ('rvm', 'RVM List'), ('ref', 'Reference')], max_length=16)),
                ('path', models.FileField(upload_to='resources/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
            },
        ),
    ]
