# Generated by Django 3.1.4 on 2020-12-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('VRC', 'VRC'), ('vSTARS', 'vSTARS'), ('vERAM', 'vERAM'), ('vATIS', 'vATIS'), ('SOP', 'SOP'), ('LOA', 'LOA'), ('MAVP', 'MAVP'), ('Misc', 'Misc')], max_length=16)),
                ('path', models.FileField(upload_to='resources/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
