# Generated by Django 5.0.3 on 2024-03-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('poly', 'Policy'), ('proc', 'Procedure'), ('loa', 'LOA'), ('vatis', 'vATIS Profile'), ('rvm', 'RVM List'), ('ref', 'Reference')], max_length=16),
        ),
    ]
