# Generated by Django 3.2.4 on 2023-10-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210509_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('POLY', 'Policies'), ('PROC', 'Procedures'), ('LOA', 'LOAs'), ('RVM', 'RVM Lists'), ('REF', 'References')], max_length=16),
        ),
    ]
