# Generated by Django 3.2.4 on 2023-10-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('POLY', 'Policy'), ('PROC', 'Procedure'), ('LOA', 'LOA'), ('vATIS', 'vATIS Profile'), ('RVM', 'RVM List'), ('REF', 'Reference')], max_length=16),
        ),
    ]
