# Generated by Django 3.1.7 on 2021-05-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loa',
            options={'verbose_name': 'LOA'},
        ),
    ]
