# Generated by Django 3.1.4 on 2020-12-11 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('movements', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=3)),
                ('position', models.CharField(max_length=16)),
                ('type', models.IntegerField(choices=[(0, 'Classroom'), (1, 'Sweatbox'), (2, 'Online'), (3, 'OTS')])),
                ('level', models.IntegerField(choices=[(0, 'Minor Ground'), (1, 'Major Ground'), (2, 'Minor Tower'), (3, 'Major Tower'), (4, 'Minor Approach'), (5, 'Major Approach'), (6, 'Center'), (7, 'Oceanic')])),
                ('status', models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Completed'), (2, 'Cancelled'), (3, 'No-Show')], default=0)),
                ('ots_status', models.IntegerField(choices=[(0, 'Non-OTS'), (1, 'Passed'), (2, 'Failed'), (3, 'Recommended')], default=0)),
                ('ctrs_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('solo_granted', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Training Sessions',
            },
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(0, 'Classroom'), (1, 'Sweatbox'), (2, 'Online'), (3, 'OTS')])),
                ('level', models.IntegerField(choices=[(0, 'Minor Ground'), (1, 'Major Ground'), (2, 'Minor Tower'), (3, 'Major Tower'), (4, 'Minor Approach'), (5, 'Major Approach'), (6, 'Center'), (7, 'Oceanic')])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Training Request',
            },
        ),
    ]
