# Generated by Django 5.0.3 on 2024-04-07 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(0, 'Classroom'), (1, 'Sweatbox'), (2, 'Online'), (3, 'OTS')])),
                ('level', models.IntegerField(choices=[(0, 'Ground'), (1, 'Ground (T1)'), (2, 'Tower'), (3, 'Tower (T1)'), (4, 'Approach'), (5, 'Approach (T1)'), (6, 'Center (T2)')])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training request',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('movements', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=3)),
                ('position', models.CharField(blank=True, max_length=16, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Classroom'), (1, 'Sweatbox'), (2, 'Online'), (3, 'OTS')])),
                ('level', models.IntegerField(choices=[(0, 'Ground'), (1, 'Ground (T1)'), (2, 'Tower'), (3, 'Tower (T1)'), (4, 'Approach'), (5, 'Approach (T1)'), (6, 'Center (T2)')])),
                ('status', models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Completed'), (2, 'Cancelled'), (3, 'No-Show')], default=0)),
                ('ots_status', models.IntegerField(choices=[(0, 'Non-OTS'), (1, 'Passed'), (2, 'Failed'), (3, 'Recommended')], default=0)),
                ('ctrs_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('solo_granted', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training session',
            },
        ),
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor availability',
                'unique_together': {('user', 'day')},
            },
        ),
    ]
