# Generated by Django 3.1.4 on 2020-12-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(0, 'Classroom'), (1, 'Sweatbox'), (2, 'Online'), (3, 'OTS')])),
                ('level', models.IntegerField(choices=[(0, 'Minor Ground'), (1, 'Major Ground'), (2, 'Minor Tower'), (3, 'Major Tower'), (4, 'Minor Approach'), (5, 'Major Approach'), (6, 'Center'), (7, 'Oceanic')])),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Training Requests',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('movements', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=3)),
                ('position', models.CharField(max_length=16)),
                ('type', models.IntegerField(choices=[(0, 'Classroom'), (1, 'Sweatbox'), (2, 'Online'), (3, 'OTS')])),
                ('level', models.IntegerField(choices=[(0, 'Minor Ground'), (1, 'Major Ground'), (2, 'Minor Tower'), (3, 'Major Tower'), (4, 'Minor Approach'), (5, 'Major Approach'), (6, 'Center'), (7, 'Oceanic')])),
                ('status', models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Completed'), (2, 'Cancelled'), (3, 'No-Show')], default=0)),
                ('ots_status', models.IntegerField(choices=[(0, 'Non-OTS'), (1, 'Passed'), (2, 'Failed'), (3, 'Recommended')], default=0)),
                ('ctrs_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('solo_granted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Training Sessions',
            },
        ),
    ]
