# Generated by Django 5.0.3 on 2024-03-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='level',
            field=models.IntegerField(choices=[(0, 'Ground'), (1, 'Ground (T1)'), (2, 'Tower'), (3, 'Tower (T1)'), (4, 'Approach'), (5, 'Approach (T1)'), (6, 'Center (T2)')]),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='level',
            field=models.IntegerField(choices=[(0, 'Ground'), (1, 'Ground (T1)'), (2, 'Tower'), (3, 'Tower (T1)'), (4, 'Approach'), (5, 'Approach (T1)'), (6, 'Center (T2)')]),
        ),
    ]
