# Generated by Django 3.1.4 on 2020-12-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20201211_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingrequest',
            old_name='student',
            new_name='user',
        ),
    ]
