# Generated by Django 3.2.4 on 2022-05-11 23:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0005_mentoravailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentoravailability',
            unique_together={('user', 'day')},
        ),
    ]
