# Generated by Django 3.2.4 on 2022-05-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_mentoravailability_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoravailability',
            name='day',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
    ]
