# Generated by Django 3.2.4 on 2023-10-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_mentoravailability_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequest',
            name='level',
            field=models.IntegerField(choices=[(0, 'Minor Ground'), (1, 'Major Ground'), (2, 'Minor Tower'), (3, 'Major Tower'), (4, 'Minor Approach'), (5, 'Major Approach'), (6, 'Center')]),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='level',
            field=models.IntegerField(choices=[(0, 'Minor Ground'), (1, 'Major Ground'), (2, 'Minor Tower'), (3, 'Major Tower'), (4, 'Minor Approach'), (5, 'Major Approach'), (6, 'Center')]),
        ),
    ]
