# Generated by Django 5.0.3 on 2024-04-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.EmailField(max_length=254),
        ),
    ]
