# Generated by Django 5.0.3 on 2024-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=16)),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
            options={
                'verbose_name': 'Controller session',
            },
        ),
        migrations.CreateModel(
            name='OnlineController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=16)),
                ('online_since', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Online controller',
            },
        ),
    ]
