# Generated by Django 3.1.7 on 2021-05-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_auto_20201224_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controllersession',
            options={'verbose_name': 'Controller session'},
        ),
        migrations.AlterModelOptions(
            name='onlinecontroller',
            options={'verbose_name': 'Online controller'},
        ),
    ]
