# Generated by Django 3.1.4 on 2020-12-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=16)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('pilot_cid', models.IntegerField()),
                ('pilot_name', models.CharField(blank=True, max_length=64, null=True)),
                ('pilot_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pilot_callsign', models.CharField(blank=True, max_length=16, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
