# Generated by Django 5.0.3 on 2024-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_callsign', models.CharField(blank=True, max_length=16, null=True)),
                ('pilot_callsign', models.CharField(blank=True, max_length=16, null=True)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
