# Generated by Django 3.1.4 on 2020-12-11 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=16)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('pilot_cid', models.IntegerField()),
                ('pilot_name', models.CharField(blank=True, max_length=64, null=True)),
                ('pilot_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pilot_callsign', models.CharField(blank=True, max_length=16, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_feedback', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
