# Generated by Django 3.1.4 on 2021-01-12 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0003_auto_20210111_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='controller_callsign',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
