# Generated by Django 3.1.4 on 2021-01-06 23:11

import apps.users.models
from django.db import migrations, models
import zhu_core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, storage=zhu_core.utils.OverwriteStorage(), upload_to=apps.users.models.create_profile_path),
        ),
    ]
