# Generated by Django 3.1.4 on 2021-02-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210106_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prevent_event_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='users.Role'),
        ),
    ]
