# Generated by Django 3.1.4 on 2020-12-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_home_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_cert',
            field=models.IntegerField(choices=[(0, 'No Certification'), (1, 'Minor Certification'), (2, 'Major Certification'), (3, 'Solo Certification')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ctr_cert',
            field=models.IntegerField(choices=[(0, 'No Certification'), (1, 'Minor Certification'), (2, 'Major Certification'), (3, 'Solo Certification')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='del_cert',
            field=models.IntegerField(choices=[(0, 'No Certification'), (1, 'Minor Certification'), (2, 'Major Certification'), (3, 'Solo Certification')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gnd_cert',
            field=models.IntegerField(choices=[(0, 'No Certification'), (1, 'Minor Certification'), (2, 'Major Certification'), (3, 'Solo Certification')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ocn_cert',
            field=models.IntegerField(choices=[(0, 'No Certification'), (1, 'Minor Certification'), (2, 'Major Certification'), (3, 'Solo Certification')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='twr_cert',
            field=models.IntegerField(choices=[(0, 'No Certification'), (1, 'Minor Certification'), (2, 'Major Certification'), (3, 'Solo Certification')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Loa'), (2, 'Non Member')], default=2),
        ),
    ]
