# Generated by Django 3.1.7 on 2021-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_cic_endorsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.CharField(choices=[('', 'Unknown'), ('OBS', 'Observer'), ('S1', 'Student 1'), ('S2', 'Student 2'), ('S3', 'Student 3'), ('C1', 'Controller'), ('C3', 'Senior Controller'), ('I1', 'Instructor'), ('I3', 'Senior Instructor'), ('SUP', 'Supervisor'), ('ADM', 'Administrator')], max_length=3),
        ),
    ]
