# Generated by Django 3.2.4 on 2023-10-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_solo_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ocn_cert',
        ),
    ]
