# Generated by Django 3.2.4 on 2023-10-17 17:03

from django.db import migrations
from django.db.models import Q


def remove_default_profiles(apps, schema_editor):
    User = apps.get_model("users", "User")
    db_alias = schema_editor.connection.alias

    no_profile = Q(profile__contains="default") | Q(profile="")
    User.objects.using(db_alias).filter(no_profile).update(profile=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_ocn_cert'),
    ]

    operations = [
        migrations.RunPython(remove_default_profiles)
    ]
