# Generated by Django 5.0.3 on 2024-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=4)),
                ('config_profile', models.CharField(max_length=16)),
                ('atis_letter', models.CharField(max_length=1)),
                ('airport_conditions', models.TextField()),
                ('notams', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ATIS',
                'verbose_name_plural': 'ATIS',
            },
        ),
        migrations.CreateModel(
            name='METAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=4)),
                ('raw', models.TextField()),
                ('flight_rules', models.CharField(max_length=4)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'METAR',
            },
        ),
        migrations.CreateModel(
            name='TMUNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('time_issued', models.DateTimeField(auto_now_add=True)),
                ('time_expires', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'TMU notice',
            },
        ),
    ]
