# Generated by Django 3.1.4 on 2020-12-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=4)),
                ('config_profile', models.CharField(max_length=16)),
                ('atis_letter', models.CharField(max_length=1)),
                ('airport_conditions', models.TextField()),
                ('notams', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ATIS',
            },
        ),
        migrations.CreateModel(
            name='TMUNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('time_issued', models.DateTimeField(auto_now_add=True)),
                ('time_expires', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'TMU Notices',
            },
        ),
    ]
