# Generated by Django 3.1.4 on 2021-01-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='METAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=4)),
                ('raw', models.TextField()),
                ('flight_rules', models.CharField(max_length=4)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'METARs',
            },
        ),
    ]
