# Generated by Django 3.1.4 on 2020-12-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atis',
            options={'verbose_name_plural': 'ATIS'},
        ),
        migrations.AlterModelOptions(
            name='tmunotice',
            options={'verbose_name_plural': 'TMU Notices'},
        ),
    ]
