# Generated by Django 3.1.7 on 2021-05-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmu', '0002_metar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atis',
            options={'verbose_name': 'ATIS', 'verbose_name_plural': 'ATIS'},
        ),
        migrations.AlterModelOptions(
            name='metar',
            options={'verbose_name': 'METAR'},
        ),
        migrations.AlterModelOptions(
            name='tmunotice',
            options={'verbose_name': 'TMU notice'},
        ),
    ]
